export const STACK_OPTIONS = [
  {
    id: "electron-rn-nestjs",
    label: "Electron + React Native + NestJS",
    sdk: "libsignal",
  },
  {
    id: "nextjs-supabase",
    label: "Next.js + Supabase + React Native",
    sdk: "Matrix SDK",
  },
  {
    id: "flutter-go",
    label: "Flutter + Go + PostgreSQL",
    sdk: "libsignal",
  },
  {
    id: "vue-fastapi",
    label: "Vue 3 + FastAPI + Redis",
    sdk: "Matrix SDK",
  },
] as const;

export const SDK_OPTIONS = ["libsignal", "Matrix SDK"] as const;

export type StackId = (typeof STACK_OPTIONS)[number]["id"];
export type SdkOption = (typeof SDK_OPTIONS)[number];

export const CODE_SAMPLES: Record<
  StackId,
  { filename: string; language: string; code: string; files: string[] }
> = {
  "electron-rn-nestjs": {
    filename: "signal-bridge.service.ts",
    language: "typescript",
    files: [
      "signal-bridge.service.ts",
      "prekey-bundle.controller.ts",
      "session-store.module.ts",
      "electron/preload-signal.ts",
      "mobile/SignalProvider.tsx",
    ],
    code: `// NestJS Signal Bridge — auto-generated by CipherBridge
import { Injectable, OnModuleInit } from '@nestjs/common';
import {
  SignalProtocolStore,
  SessionBuilder,
  PreKeyBundle,
} from '@privacyresearch/libsignal-protocol-typescript';

@Injectable()
export class SignalBridgeService implements OnModuleInit {
  private store: SignalProtocolStore;

  async onModuleInit() {
    this.store = await this.bootstrapStore(process.env.SIGNAL_DEVICE_ID!);
  }

  /** Establish E2EE session with remote device prekey bundle */
  async initSession(recipientId: string, bundle: PreKeyBundle) {
    const builder = new SessionBuilder(this.store, recipientId);
    await builder.processPreKeyBundle(bundle);
    return { status: 'session_established', recipientId };
  }

  /** Encrypt outbound message for delivery queue */
  async encryptMessage(recipientId: string, plaintext: Uint8Array) {
    const sessionCipher = this.createCipher(recipientId);
    const ciphertext = await sessionCipher.encrypt(plaintext);
    return {
      type: ciphertext.type,
      body: Buffer.from(ciphertext.body!).toString('base64'),
      registrationId: await this.store.getLocalRegistrationId(),
    };
  }

  private async bootstrapStore(deviceId: string) {
    // Backed by encrypted SQLite on Electron, SecureStore on RN
    return new SignalProtocolStore(/* ... */);
  }
}`,
  },
  "nextjs-supabase": {
    filename: "matrix-client.ts",
    language: "typescript",
    files: [
      "matrix-client.ts",
      "hooks/useMatrixRoom.ts",
      "api/sync-handler.ts",
      "mobile/MatrixSyncProvider.tsx",
    ],
    code: `// Matrix SDK Client — auto-generated by CipherBridge
import * as sdk from 'matrix-js-sdk';
import { createClient, MatrixClient, IContent } from 'matrix-js-sdk';

export function createMatrixClient(opts: {
  baseUrl: string;
  accessToken: string;
  userId: string;
  deviceId: string;
}): MatrixClient {
  const client = createClient({
    baseUrl: opts.baseUrl,
    accessToken: opts.accessToken,
    userId: opts.userId,
    deviceId: opts.deviceId,
    cryptoStore: new sdk.IndexedDBCryptoStore(/* ... */),
    store: new sdk.IndexedDBStore(/* ... */),
  });

  client.initCrypto().then(() => client.startClient({ initialSyncLimit: 20 }));
  return client;
}

/** Send encrypted room message with Olm/Megolm */
export async function sendEncryptedMessage(
  client: MatrixClient,
  roomId: string,
  body: string,
): Promise<void> {
  const content: IContent = { msgtype: 'm.text', body };
  await client.sendEvent(roomId, 'm.room.message', content);
}`,
  },
  "flutter-go": {
    filename: "signal_handler.go",
    language: "go",
    files: [
      "internal/signal/handler.go",
      "internal/signal/prekey_store.go",
      "lib/services/signal_service.dart",
      "lib/widgets/e2ee_chat.dart",
    ],
    code: `// Go Signal Handler — auto-generated by CipherBridge
package signal

import (
	"context"
	"encoding/base64"

	"github.com/Rhymen/go-libsignal/serialize"
	"github.com/Rhymen/go-libsignal/session"
	"github.com/Rhymen/go-libsignal/state/record"
)

type Handler struct {
	store   *ProtocolStore
	builder *session.Builder
}

func NewHandler(store *ProtocolStore, address string) *Handler {
	return &Handler{
		store:   store,
		builder: session.NewBuilder(store, store, store, store, address, 1),
	}
}

func (h *Handler) Encrypt(ctx context.Context, plaintext []byte) (string, error) {
	cipher := session.NewCipher(h.builder, h.store, h.store, h.store, h.store, address, 1)
	msg, err := cipher.Encrypt(plaintext)
	if err != nil {
		return "", err
	}
	serialized, _ := serialize.Serialize(msg)
	return base64.StdEncoding.EncodeToString(serialized), nil
}`,
  },
  "vue-fastapi": {
    filename: "matrix_sync.py",
    language: "python",
    files: [
      "app/services/matrix_sync.py",
      "app/routers/e2ee_messages.py",
      "app/workers/delivery_queue.py",
      "frontend/composables/useMatrix.ts",
    ],
    code: `# Matrix Sync Service — auto-generated by CipherBridge
from nio import AsyncClient, RoomMessageText, MegolmEvent
from nio.crypto import ENCRYPTION_ENABLED
import asyncio

class MatrixSyncService:
    def __init__(self, homeserver: str, user_id: str, token: str):
        self.client = AsyncClient(homeserver, user_id)
        self.client.access_token = token

    async def start(self):
        await self.client.sync(timeout=30000)
        self.client.add_event_callback(self._on_message, RoomMessageText)
        self.client.add_event_callback(self._on_encrypted, MegolmEvent)
        await self.client.sync_forever(timeout=30000)

    async def _on_encrypted(self, room, event):
        # Megolm group message — decrypt and enqueue for offline delivery
        decrypted = await self.client.decrypt_event(event)
        await self.delivery_queue.enqueue(room.room_id, decrypted)

    async def send_encrypted(self, room_id: str, body: str):
        await self.client.room_send(
            room_id, "m.room.message",
            {"msgtype": "m.text", "body": body},
        )`,
  },
};

export const KEY_WIZARD_STEPS = [
  {
    id: "identity",
    title: "Identity Key Pair",
    description: "Generate long-term Curve25519 identity keys stored in platform secure enclave.",
    annotation:
      "Identity keys never leave the device. CipherBridge scaffolds HSM/Keychain integration per platform.",
  },
  {
    id: "prekeys",
    title: "One-Time Prekey Batch",
    description: "Upload 100 signed prekeys to server; replenish when count drops below threshold.",
    annotation:
      "Auto-replenish hook triggers when prekey count < 20. Includes signed prekey rotation every 7 days.",
  },
  {
    id: "link",
    title: "Multi-Device Linking",
    description: "QR-based device linking with Safety Number verification flow.",
    annotation:
      "Linked devices share session state via encrypted sync channel. Primary device approves new links.",
  },
  {
    id: "revoke",
    title: "Device Revocation",
    description: "Revoke compromised devices and rotate sender keys for all active group chats.",
    annotation:
      "Revocation propagates via server-side device list update + client-side sender key reset.",
  },
];

export const KEY_WIZARD_CODE = `// Multi-device key rotation — CipherBridge wizard output
async function rotateSignedPreKey(store: SignalProtocolStore) {
  const identityKeyPair = await store.getIdentityKeyPair();
  const newSignedPreKey = KeyHelper.generateSignedPreKey(
    identityKeyPair,
    store.getNextSignedPreKeyId(),
  );

  await store.storeSignedPreKey(newSignedPreKey.keyId, newSignedPreKey.keyPair);
  await store.storeSignedPreKeySignature(
    newSignedPreKey.keyId,
    newSignedPreKey.signature,
  );

  // Upload to prekey server — triggers replenishment webhook
  await prekeyServer.uploadSignedPreKey({
    keyId: newSignedPreKey.keyId,
    publicKey: newSignedPreKey.keyPair.pubKey,
    signature: newSignedPreKey.signature,
  });

  return { rotatedAt: Date.now(), nextRotation: Date.now() + 7 * 86400000 };
}`;

export const QUEUE_CODE = `// Offline delivery queue with retry + receipt semantics
interface QueuedMessage {
  id: string;
  recipientId: string;
  ciphertext: string;
  attempts: number;
  maxAttempts: 5;
  status: 'pending' | 'delivered' | 'failed';
  createdAt: number;
}

class OfflineDeliveryQueue {
  private queue: QueuedMessage[] = [];
  private retryDelays = [1000, 5000, 30000, 120000, 300000]; // ms

  async enqueue(msg: Omit<QueuedMessage, 'attempts' | 'status'>) {
    this.queue.push({ ...msg, attempts: 0, status: 'pending' });
    await this.persist();
    this.processNext();
  }

  private async processNext() {
    const msg = this.queue.find(m => m.status === 'pending');
    if (!msg) return;

    try {
      const receipt = await this.transport.send(msg);
      if (receipt.delivered) {
        msg.status = 'delivered';
        await this.notifySender(msg.id, receipt);
      }
    } catch (err) {
      msg.attempts++;
      if (msg.attempts >= msg.maxAttempts) {
        msg.status = 'failed';
      } else {
        setTimeout(() => this.processNext(), this.retryDelays[msg.attempts - 1]);
      }
    }
    await this.persist();
  }
}`;

export const GROUP_SCHEMA_CODE = `// Group key distribution — Megolm sender keys
interface GroupSession {
  roomId: string;
  senderKey: Uint8Array;
  sessionId: string;
  memberDevices: DeviceId[];
  epoch: number;
}

class GroupKeyManager {
  async createGroup(creatorId: string, memberIds: string[]): Promise<GroupSession> {
    const senderKey = crypto.getRandomValues(new Uint8Array(32));
    const session = {
      roomId: generateRoomId(),
      senderKey,
      sessionId: uuid(),
      memberDevices: [],
      epoch: 1,
    };

    // Distribute encrypted sender keys to each member device
    for (const memberId of memberIds) {
      const devices = await this.deviceStore.getActiveDevices(memberId);
      for (const device of devices) {
        const wrapped = await this.encryptForDevice(device, senderKey);
        await this.distributeKey(session.roomId, device.id, wrapped);
      }
    }
    return session;
  }

  async addMember(session: GroupSession, newMemberId: string) {
    session.epoch++;
    const newSenderKey = crypto.getRandomValues(new Uint8Array(32));
    // Rotate sender key on member add — forward secrecy
    await this.redistributeKeys(session, newSenderKey, [...session.memberDevices, newMemberId]);
  }

  async removeMember(session: GroupSession, removedMemberId: string) {
    session.epoch++;
    const newSenderKey = crypto.getRandomValues(new Uint8Array(32));
    const remaining = session.memberDevices.filter(d => d.userId !== removedMemberId);
    await this.redistributeKeys(session, newSenderKey, remaining);
  }
}`;

export const TROUBLESHOOTING_SAMPLES = [
  {
    id: "prekey-bundle",
    prompt: "InvalidPreKeyBundle: missing signed prekey signature",
    log: `Error: InvalidPreKeyBundle
  at SessionBuilder.processPreKeyBundle (libsignal-protocol.js:892)
  at SignalBridgeService.initSession (signal-bridge.service.ts:34)
  
Device 3 registration failed — signed prekey signature verification returned false.`,
    response: {
      diagnosis:
        "The signed prekey signature verification failed because the identity key used to sign the prekey doesn't match the identity key in the bundle. This typically happens when prekeys were generated on a different device or after an identity key rotation without re-uploading.",
      fix: `// Fix: Re-generate and upload signed prekey with current identity key
const identityKey = await store.getIdentityKeyPair();
const signedPreKey = KeyHelper.generateSignedPreKey(
  identityKey,
  await store.getNextSignedPreKeyId(),
);

// CRITICAL: Use the SAME identity key that is registered on the server
await prekeyServer.uploadBundle({
  identityKey: identityKey.pubKey,
  signedPreKey: {
    keyId: signedPreKey.keyId,
    publicKey: signedPreKey.keyPair.pubKey,
    signature: signedPreKey.signature, // Must sign with identityKey.privKey
  },
  oneTimePreKeys: await generateOneTimePreKeys(100),
});`,
      explanation:
        "Ensure your identity key pair is persisted before generating signed prekeys. If you rotated identity keys, all devices must fetch the new bundle before session establishment.",
    },
  },
  {
    id: "megolm-decrypt",
    prompt: "Unable to decrypt Megolm event — M_MISSING_SESSION",
    log: `WARN matrix-js-sdk: Event $abc123: Unable to decrypt Megolm event
  code: M_MISSING_SESSION
  room: !roomId:matrix.org
  sender: @alice:matrix.org
  
Session sharing keys not received for sender device XYZABCDE.`,
    response: {
      diagnosis:
        "The client is missing the Megolm inbound group session for this sender. This occurs when a device joins a room after messages were sent, or when the sender key wasn't shared via Olm-encrypted to-device messages.",
      fix: `// Request missing session keys from room members
client.on('Room.timeline', (event, room) => {
  if (event.isEncrypted() && !event.getClearContent()) {
    // Trigger key request — Matrix SDK handles this automatically
    // but you must ensure crypto is initialized BEFORE sync
    client.reEmitter.emit('crypto.missingSession', {
      roomId: room.roomId,
      senderKey: event.getSenderKey(),
    });
  }
});

// Ensure init order:
await client.initCrypto();
await client.startClient({ initialSyncLimit: 0 });
// Do NOT send messages until first sync completes`,
      explanation:
        "Call initCrypto() before startClient(). For new devices, request a key backup or ask another member to re-share sender keys via /keys/query.",
    },
  },
  {
    id: "session-corrupt",
    prompt: "Bad MAC on decrypt — session state corrupted",
    log: `Error: Bad MAC
  at SessionCipher.decryptPreKeyWhisperMessage
  recipient: user_8821 device 2
  
Possible duplicate message or session desync after device restore.`,
    response: {
      diagnosis:
        "Session state desync — the local session record doesn't match the remote's ratchet state. Common after restoring from backup or processing the same PreKeyWhisperMessage twice.",
      fix: `// Reset session and re-establish with fresh prekey bundle
async function resetSession(recipientId: string, deviceId: number) {
  const address = new SignalProtocolAddress(recipientId, deviceId);
  await store.deleteSession(address);
  await store.deleteAllSessions(recipientId);

  const bundle = await prekeyServer.fetchBundle(recipientId, deviceId);
  const builder = new SessionBuilder(store, address);
  await builder.processPreKeyBundle(bundle);
}

// Add idempotency guard for message processing
const processedIds = new Set<string>();
function shouldProcess(messageId: string): boolean {
  if (processedIds.has(messageId)) return false;
  processedIds.add(messageId);
  return true;
}`,
      explanation:
        "Never restore Signal session state from server-side backups. Sessions are device-local. After reset, the next message will re-establish via prekey bundle.",
    },
  },
];
